<?php

$plugin_cf['hi_fancybox']['activate_global']="true";
$plugin_cf['hi_fancybox']['activate_mousewheel']="true";
$plugin_cf['hi_fancybox']['activate_touchsupport']="true";
$plugin_cf['hi_fancybox']['nav_duration_hide']="2000";
$plugin_cf['hi_fancybox']['nav_hide_title']="true";
$plugin_cf['hi_fancybox']['class_single']="a.zoom";
$plugin_cf['hi_fancybox']['class_group']="a.zoom_g";
$plugin_cf['hi_fancybox']['class_iframe']="a.zoom_i";
$plugin_cf['hi_fancybox']['fcb_padding']="10";
$plugin_cf['hi_fancybox']['fcb_margin']="20";
$plugin_cf['hi_fancybox']['fcb_opacity']="true";
$plugin_cf['hi_fancybox']['fcb_cyclic']="";
$plugin_cf['hi_fancybox']['fcb_scrolling']="'auto'";
$plugin_cf['hi_fancybox']['fcb_width']="'75%'";
$plugin_cf['hi_fancybox']['fcb_height']="'75%'";
$plugin_cf['hi_fancybox']['fcb_autoScale']="true";
$plugin_cf['hi_fancybox']['fcb_centerOnScroll']="true";
$plugin_cf['hi_fancybox']['fcb_hideOnOverlayClick']="true";
$plugin_cf['hi_fancybox']['fcb_overlayShow']="true";
$plugin_cf['hi_fancybox']['fcb_overlayOpacity']="0.3";
$plugin_cf['hi_fancybox']['fcb_overlayColor']="'#666'";
$plugin_cf['hi_fancybox']['fcb_titleShow']="true";
$plugin_cf['hi_fancybox']['fcb_titlePosition']="'over'";
$plugin_cf['hi_fancybox']['fcb_transitionIn']="'elastic'";
$plugin_cf['hi_fancybox']['fcb_transitionOut']="'fade'";
$plugin_cf['hi_fancybox']['fcb_speedIn']="300";
$plugin_cf['hi_fancybox']['fcb_speedOut']="300";
$plugin_cf['hi_fancybox']['fcb_changeSpeed']="300";
$plugin_cf['hi_fancybox']['fcb_changeFade']="'fast'";
$plugin_cf['hi_fancybox']['fcb_easingIn']="'linear'";
$plugin_cf['hi_fancybox']['fcb_easingOut']="'swing'";
$plugin_cf['hi_fancybox']['fcb_showCloseButton']="true";
$plugin_cf['hi_fancybox']['fcb_enableEscapeButton']="true";
$plugin_cf['hi_fancybox']['fcb_showIframeLoading']="true";

?>
