<?php

$plugin_mcf['hi_fancybox']['activate_global']="bool";
$plugin_mcf['hi_fancybox']['activate_mousewheel']="bool";
$plugin_mcf['hi_fancybox']['activate_touchsupport']="bool";
$plugin_mcf['hi_fancybox']['nav_duration_hide']="string";
$plugin_mcf['hi_fancybox']['nav_hide_title']="bool";
$plugin_mcf['hi_fancybox']['class_single']="string";
$plugin_mcf['hi_fancybox']['class_group']="string";
$plugin_mcf['hi_fancybox']['class_iframe']="string";
$plugin_mcf['hi_fancybox']['fcb_padding']="string";
$plugin_mcf['hi_fancybox']['fcb_margin']="string";
$plugin_mcf['hi_fancybox']['fcb_opacity']="bool";
$plugin_mcf['hi_fancybox']['fcb_cyclic']="bool";
$plugin_mcf['hi_fancybox']['fcb_scrolling']="enum:'auto','yes','no'";
$plugin_mcf['hi_fancybox']['fcb_width']="string";
$plugin_mcf['hi_fancybox']['fcb_height']="string";
$plugin_mcf['hi_fancybox']['fcb_autoScale']="bool";
$plugin_mcf['hi_fancybox']['fcb_centerOnScroll']="bool";
$plugin_mcf['hi_fancybox']['fcb_hideOnOverlayClick']="bool";
$plugin_mcf['hi_fancybox']['fcb_overlayShow']="bool";
$plugin_mcf['hi_fancybox']['fcb_overlayOpacity']="enum:0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1";
$plugin_mcf['hi_fancybox']['fcb_overlayColor']="string";
$plugin_mcf['hi_fancybox']['fcb_titleShow']="bool";
$plugin_mcf['hi_fancybox']['fcb_titlePosition']="enum:'float','inside','over'";
$plugin_mcf['hi_fancybox']['fcb_transitionIn']="enum:'elastic','fade','none'";
$plugin_mcf['hi_fancybox']['fcb_transitionOut']="enum:'elastic','fade','none'";
$plugin_mcf['hi_fancybox']['fcb_speedIn']="string";
$plugin_mcf['hi_fancybox']['fcb_speedOut']="string";
$plugin_mcf['hi_fancybox']['fcb_changeSpeed']="string";
$plugin_mcf['hi_fancybox']['fcb_changeFade']="enum:'fast','slow'";
$plugin_mcf['hi_fancybox']['fcb_easingIn']="enum:'linear','swing'";
$plugin_mcf['hi_fancybox']['fcb_easingOut']="enum:'linear','swing'";
$plugin_mcf['hi_fancybox']['fcb_showCloseButton']="bool";
$plugin_mcf['hi_fancybox']['fcb_enableEscapeButton']="bool";
$plugin_mcf['hi_fancybox']['fcb_showIframeLoading']="bool";

?>